  name: Android Fastlane Firebase App Distribution Workflow
  on:
    push:
      branches:
        - master
  jobs:
    distribute_to_firebase:
      runs-on: ubuntu-latest
      steps:
        - name: Check My repo Code
          uses: actions/checkout@v2


        - name: Set up Java JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'


        - name: Install Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'


        - name: Install Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.2.3
            bundler-cache: true
            working-directory: android

        - name: Build and Distribute App
          env:
            FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          run: bundle exec fastlane firebase_distribution --verbose
          working-directory: android