  name: Android Fastlane Firebase App Distribution Workflow
  on:
    push:
      branches:
        - master
  jobs:
    distribute_to_firebase:
      name: Build DocDoc App
      runs-on: ubuntu-latest
      steps:
        - name: Check My repo Code
          uses: actions/checkout@v4


        - name: Set up Java JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'


        - name: Install Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        - run: flutter clean
        - run: flutter pub get
        - run: flutter build apk --release --flavor production -t lib/main_production.dart
        - uses: actions/upload-artifact@v4.3.6
          with:
            name: DocDoc Production App
            path: build/app/outputs/apk/release


        - name: Install Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.2.4
            bundler-cache: true
            working-directory: android

        - name: Build and Distribute App
          env:
            FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          run: bundle exec fastlane firebase_android_distribution
          working-directory: android